---
- name: Check if Unifi
  stat:
    path: "/etc/init.d/unifi"
  register: unifi_stat

- include: unifi.yml
  when: (unifi_stat.stat.exists)

- include: certificate-check.yml
  when: (unifi_stat.stat.exists)

- include: common.yml
  when: (unifi_stat.stat.exists) and (not certificate_match)

- name: Check if Unifi-Video
  stat:
    path: "/etc/init.d/unifi-video"
  register: unifi_video_stat

- include: unifi-video.yml
  when: (unifi_video_stat.stat.exists)

- include: certificate-check.yml
  when: (unifi_video_stat.stat.exists)

- include: common.yml
  when: (unifi_video_stat.stat.exists) and (not certificate_match)